# Generated by Django 3.0.5 on 2020-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myassignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField(verbose_name='max_length=100')),
                ('task_purpose', models.TextField(verbose_name='max_length=100')),
                ('task_key_goal_indicators', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
