# Generated by Django 3.0.5 on 2020-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_app', '0002_auto_20200504_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myassignment',
            name='task_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myassignment',
            name='task_purpose',
            field=models.TextField(max_length=500),
        ),
    ]
